name: Deploy Microservices Manuales
on:
  push:
    branches:
      - "main"

  # Esta instruccion permite llamar manualmente el Action
  workflow_dispatch:

env:
  ENVIRONMENT: "dev"

jobs:
  release_dga_bp_to_raw:
    name: "Dga bp to raw dev"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: zipdgabptoraw
        run: |
          cd ./dga_bp_to_raw/
          ls
          zip -r ./microservice.zip  ./*
      - name: dgacheckbpdeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_DEFAULT_OUTPUT: "json"
        run: aws lambda update-function-code --function-name "dga_bp_to_raw_$ENVIRONMENT" --zip-file fileb://microservice.zip
